### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by s4m-mo** [yoshiask/ManimInteractive#5]
Would it be possible for a GitHub release on this repo with a binary distribution I can use, since I have no experience with C#, but love using Manim in Python.

Many thanks.

**Comment by yoshiask** [comment]
Howdy! I haven't touched this project in a very long time, and Manim has changed a lot. If you're already using an ancient version of Manim (not ManimCE), you might be able to use [this](https://github.com/yoshiask/ManimInteractive/blob/f18395a0e2785a2c8196a2273e20d1122aad4dd8/ManimInteractive/ManimInteractive_5-27-2019.zip). Updating Manim Interactive to the latest version of Manim or ManimCE is non-trivial and probably won't happen anytime soon (at least not by myself).
